In [1]:
import torch

In [2]:
x = torch.empty(1)
print(x)

tensor([0.])


In [3]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(3,3)
print(x)

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [7]:
x = torch.empty(2,3,2)
print(x)

tensor([[[1.0286e-38, 1.0653e-38],
         [1.0194e-38, 8.4490e-39],
         [1.0469e-38, 9.3674e-39]],

        [[9.9184e-39, 8.7245e-39],
         [9.2755e-39, 8.9082e-39],
         [9.9184e-39, 8.4490e-39]]])


In [8]:
x = torch.rand(3,3)
print(x)

tensor([[0.3448, 0.9188, 0.6927],
        [0.9514, 0.6132, 0.7493],
        [0.3870, 0.8318, 0.4698]])


In [9]:
x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [13]:
x = torch.ones(3,3, dtype= torch.int32)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [15]:
A = [2.5, 0.1]
x = torch.tensor(A)
print(x)

tensor([2.5000, 0.1000])


In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x*y
z = x+y
z = x-y
print(z)
z= torch.mul(x,y)
z= torch.add(x,y)
z= torch.sub(x,y)
print(z)

tensor([[0.0279, 0.0161],
        [0.0694, 0.5798]])
tensor([[0.2814, 0.9270],
        [0.6475, 0.2050]])
tensor([[-0.2535, -0.9109],
        [-0.5781,  0.3747]])
tensor([[-0.2535, -0.9109],
        [-0.5781,  0.3747]])


In [22]:
x = torch.rand(5,3)
print(x)

tensor([[0.8283, 0.2883, 0.1176],
        [0.1128, 0.0145, 0.2286],
        [0.8356, 0.3982, 0.2577],
        [0.3336, 0.2425, 0.4647],
        [0.7438, 0.0065, 0.7989]])


In [23]:
print(x[:,0])

tensor([0.8283, 0.1128, 0.8356, 0.3336, 0.7438])


In [26]:
print(x[0:2,:])

tensor([[0.8283, 0.2883, 0.1176],
        [0.1128, 0.0145, 0.2286]])


In [29]:
print(x[0,0])
print(x[0,0].item())

tensor(0.8283)
0.8282577395439148


In [30]:
x = torch.rand(4,4)
print(x)

tensor([[0.1726, 0.8456, 0.2947, 0.6546],
        [0.7188, 0.6638, 0.5594, 0.5543],
        [0.3453, 0.7042, 0.1191, 0.6527],
        [0.9670, 0.5552, 0.6529, 0.0657]])


In [31]:
y = x.view(16)
print(y)

tensor([0.1726, 0.8456, 0.2947, 0.6546, 0.7188, 0.6638, 0.5594, 0.5543, 0.3453,
        0.7042, 0.1191, 0.6527, 0.9670, 0.5552, 0.6529, 0.0657])


In [32]:
y = x.view(2,8)
print(y)

tensor([[0.1726, 0.8456, 0.2947, 0.6546, 0.7188, 0.6638, 0.5594, 0.5543],
        [0.3453, 0.7042, 0.1191, 0.6527, 0.9670, 0.5552, 0.6529, 0.0657]])


In [33]:
y = x.view(-1,8)
print(y)

tensor([[0.1726, 0.8456, 0.2947, 0.6546, 0.7188, 0.6638, 0.5594, 0.5543],
        [0.3453, 0.7042, 0.1191, 0.6527, 0.9670, 0.5552, 0.6529, 0.0657]])
